mavros:
  ros__parameters:
    fcu_url: "udp://:14540@127.0.0.1:14557"
    gcs_url: ""
    tgt_system: 1
    tgt_component: 1
    plugin_allowlist: ["sys_status", "local_position", "pose", "tf","imu_pub","imu_accel","imu_mag"]

    use_sim_time: true

    tf:
      send: true
      frame_id: "map"
      child_frame_id: "drone_base_link"
      rate_limit: 50.0
